all: hello calculator points parity agree meow discount mario

hello: hello.c
	gcc -Wall -g -lcs50 hello.c -o hello

calculator: calculator.c
	gcc -Wall -g -lcs50 calculator.c -o calculator

points: points.c
	gcc -Wall -g -lcs50 points.c -o points

parity: parity.c
	gcc -Wall -g -lcs50 parity.c -o parity

agree: agree.c
	gcc -Wall -g -lcs50 agree.c -o agree

meow: meow.c
	gcc -Wall -g meow.c -o meow

discount: discount.c
	gcc -Wall -g -lcs50 discount.c -o discount

mario: mario.c
	gcc -Wall -g -lcs50 mario.c -o mario