all: hello calculator points parity

hello: hello.c
	gcc -Wall -g -lcs50 hello.c -o hello

calculator: calculator.c
	gcc -Wall -g -lcs50 calculator.c -o calculator

points: points.c
	gcc -Wall -g -lcs50 points.c -o points

parity: parity.c
	gcc -Wall -g -lcs50 parity.c -o parity
