all: hello calculator points

hello: hello.c
	gcc -Wall -g -lcs50 hello.c -o hello

calculator: calculator.c
	gcc -Wall -g -lcs50 calculator.c -o calculator

points: points.c
	gcc -Wall -g -lcs50 points.c -o points
