all: numbers names phonebook

numbers: numbers.c
	gcc -Wall -g numbers.c -o numbers

names: names.c
	gcc -Wall -g names.c -o names

phonebook: phonebook.c
	gcc -Wall -g -lcs50 phonebook.c -o phonebook
