all: numbers names phonebook recursion

numbers: numbers.c
	gcc -Wall -g numbers.c -o numbers

names: names.c
	gcc -Wall -g names.c -o names

phonebook: phonebook.c
	gcc -Wall -g -lcs50 phonebook.c -o phonebook

recursion: recursion.c
	gcc -Wall -g -lcs50 recursion.c -o recursion