all: scores length string

scores: scores.c
	gcc -Wall -g -lcs50 scores.c -o scores

length: length.c
	gcc -Wall -g -lcs50 length.c -o length

string: string.c
	gcc -Wall -g -lcs50 string.c -o string
