all: scores length string uppercase

scores: scores.c
	gcc -Wall -g -lcs50 scores.c -o scores

length: length.c
	gcc -Wall -g -lcs50 length.c -o length

string: string.c
	gcc -Wall -g -lcs50 string.c -o string

uppercase: uppercase.c
	gcc -Wall -g -lcs50 uppercase.c -o uppercase
