all: plurality_1 plurality_2

plurality_1: plurality_1st_try.c
	gcc -Wall -g -lcs50 plurality_1st_try.c -o plurality_1st_try

plurality_2: plurality_2st_try.c
	gcc -Wall -g -lcs50 plurality_2st_try.c -o plurality_2st_try
