all: address compare copy memory

address: address.c
	gcc -Wall -g address.c -o address

compare: compare.c
	gcc -Wall -g -lcs50 compare.c -o compare

copy: copy.c
	gcc -Wall -g -lcs50 copy.c -o copy

memory: memory.c
	gcc -Wall -g -lcs50 memory.c -o memory